# Server settings (ServerProperties)
server:
  port: 8080
  context-path: /demo
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://123.57.216.193:3306/test?useUnicode=true&characterEncoding=utf-8
    username: gxb
    password: 123456

